# Generated by Django 4.2.5 on 2023-09-11 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
