# Generated by Django 4.2.5 on 2023-09-11 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='event_images/')),
                ('post_text', models.TextField(max_length=300)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
